### ISSUE TITLE
bad NonText highlight

### ISSUE THREAD

**Issue by deivid-rodriguez** [freeo/vim-kalisi#11]
Since a few days ago, I see these annoying markers at the end of every line.

![captura de pantalla de 2016-01-16 09 40 37](https://cloud.githubusercontent.com/assets/2887858/12371487/53efc578-bc35-11e5-86b3-d8142763de2b.png)

It gets fixed when doing `hi NonText NONE` or commenting out the line that touches the `NonText` group in the `kalisi.vim` file.

Since I'm tracking neovim's master and there hasn't been any changes in this plugin recently, I'm guessing this is a compatibility issue with `neovim`.

The workaround is good enough for me, but I thought I would share this through an issue, in case it can be fixed or the workaround can help others.

**Comment by freeo** [comment]
Does your vimrc contain a highlight group for trailing whitespace? There may be an issue with windows vs linux style line feeds. Also, what's your git setting for `core.autocrlf`? See https://help.github.com/articles/dealing-with-line-endings/

**Comment by deivid-rodriguez** [comment]
Hi @freeo, thanks for your reply!

No, I don't have any highlight groups in my `.vimrc` file (actually `.config/nvim/init.vim` since I'm using neovim). Except for the `hi NonText NONE` setting to workaround this issue. And my `core.autocrlf` setting is `input` as recommended for Linux, my OS.

**Comment by freeo** [comment]
When did this issue appear? Have you tried other colorschemes?

**Comment by deivid-rodriguez** [comment]
@freeo It appeared a few days against, I guess after a `neovim` upgrade (so maybe it's a `neovim`'s issue).

Sorry I haven't been very specific. Let me find an easy way for you to reproduce and I'll get back here.

**Comment by deivid-rodriguez** [comment]
Opened [an issue in neovim](https://github.com/neovim/neovim/issues/4048).

**Comment by deivid-rodriguez** [comment]
Ok, confirmed as a `(neo)vim` issue: https://github.com/neovim/neovim/issues/4040. Closing!
