### ISSUE TITLE
Use standard background color in dark version

### ISSUE THREAD

**Issue by leissa** [freeo/vim-kalisi#13]
I'm using Konsole and I really like a transparent background. In order to have the background transparent I have to set the background color to 0:
```
-    hi Normal ctermbg=238 ctermfg=252
+    hi Normal ctermbg=0 ctermfg=252                                                                       
```
Maybe, you can include an option or sth like that for you color scheme?

**Comment by leissa** [comment]
```
colorscheme kalisi
hi Normal ctermbg=NONE
hi NonText ctermbg=NONE
```
does the trick for me.

**Comment by freeo** [comment]
For the archive: This is a typical use case for your personal vimrc. If I implement an option for transparent background you would still need to activate this non-default option in your vimrc. Therefore nothing is gained by adding an option, which imo is why no colorscheme I've encountered so far implements this.

**Comment by leissa** [comment]
yes. Totally makes sense.
