### ISSUE TITLE
theme does not work anymore after spf13 update

### ISSUE THREAD

**Issue by i3d** [freeo/vim-kalisi#8]
This is probably one of the best vim themes (after solarized) so far I've used, love it, and that's why it is so painful I see it gone after a spf13 git pull update.

I use spf13's vim wholesale configuration solution and month ago I added the "Bundle freeo/vim-kalisi' to the .vimrc.bundles.local (the local one that I can add my own bundles), it works like a charm. But today, when I did a git pull from .spf13-vim-3 (which contains the symlink target of .vim), this theme no longer works. If you just install a new spf13 vim and add this theme, it should reflect what I described as well. I hope you or someone can take a look and see what might be the cause. I'd love to see it back. :) Thanks!

**Comment by freeo** [comment]
I will take a look into that this weekend - unfortunately, my Internet connection at my current work location doesn't allow it right now...

**Comment by i3d** [comment]
Ok I figured out now. The spf13 package contains this bundle

https://github.com/flazz/vim-colorschemes

and the latest update of this bundle included your 0.6.0 version of the theme and that took the precedence of the vim-kalisi that I installed separately. Apparently that the 0.6.0 somehow doesn't work with vim 7.4. By removing this version out of vim-colorschemes, everything worked.

**Comment by bronzehedwick** [comment]
@i3d can this issue be closed?

**Comment by i3d** [comment]
yes. thanks!
